name: example
description: "Example"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dev_dependencies:
  build_runner: any   # 模型生成器
  flutter_getx_i18n:
    path: ../.

flutter_getx_i18n:
  i18n_csv: lib/i18n.csv
  i18n_dart: lib/i18n.dart